name: Monthly issue metrics
on:
    workflow_dispatch:
    # push:
    #     branches: [main]

permissions:
    contents: read

jobs:
    build:
        name: issue metrics
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: read

        steps:
            - name: Run issue-metrics tool
              uses: github/issue-metrics@main
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  NON_MENTIONING_LINKS: true
                  LABELS_TO_MEASURE: "Backlog,Blocked,Done,orange"
                  SEARCH_QUERY: 'repo:edly-io/edly-team is:issue created:2025-01-01..2025-07-31 -reason:"not planned" (issue in:title OR fail in:title OR bug in:title OR fix in:title OR error in:title)'
            # - name: Create issue
            #   uses: peter-evans/create-issue-from-file@v4
            #   with:
            #       title: Monthly issue metrics report
            #       token: ${{ secrets.GITHUB_TOKEN }}
            #       content-filepath: ./issue_metrics.md
            #       assignees: <YOUR_GITHUB_HANDLE_HERE>
